language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

jobs:
  include:
    - stage: test
      script: cargo test
    - stage: benchmark
      rust: nightly # benchmarks are unstable
      os: linux
      script: git clone https://github.com/dlr-sc/tigl ../tigl && 
              cargo bench
    - stage: doc
      rust: nightly # uses some unstable features
      os: linux
      if: branch = master AND type != pull_request
      script: cargo doc --no-deps &&
              echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
              sudo pip install ghp-import &&
              ghp-import -n target/doc &&
              git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages 

