language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly

before_install:
  - curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2 | tar jxf -

jobs:
  include:
    - stage: test
      script: cargo test
    - stage: benchmark
      rust: nightly # benchmarks are unstable
      os: linux
      script: git clone https://github.com/dlr-sc/tigl ../tigl && 
              cd ../tigl &&
              git checkout v3.0.0 &&
              cd ../cpp_include_walker &&
              cargo bench
    - stage: codecov
      rust: nightly
      os: linux
      script: 
          - export CARGO_INCREMENTAL=0
          - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"
          - cargo build --verbose $CARGO_OPTIONS
          - cargo test --verbose $CARGO_OPTIONS
          - |
            zip -0 ccov.zip `find . \( -name "cpp_include_walker*.gc*" \) -print`;
            ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
            bash <(curl -s https://codecov.io/bash) -f lcov.info;
    - stage: doc
      rust: nightly # uses some unstable features
      os: linux
      if: branch = master AND type != pull_request
      script: cargo doc --no-deps &&
              echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html &&
              sudo pip install ghp-import &&
              ghp-import -n target/doc &&
              git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages 

